name: efhamnidz
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.17.0 <4.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  get: ^4.6.6
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^4.2.1
  flutter_svg_provider: ^1.0.7
  intl: ^0.18.0
  dartz: ^0.10.1
  lottie: ^3.1.0
  animated_bottom_navigation_bar: ^1.3.3
  video_player: ^2.8.5
  camera: ^0.10.5+9
  tflite: ^1.1.2
  animations: ^2.0.11
  circular_menu: ^3.0.0
  awesome_dialog: ^3.2.1
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
    - assets/images/quizimages/bism.png
    - assets/images/quizimages/allah.png
    - assets/images/quizimages/rahman.png
    - assets/images/quizimages/rahim.png
    - assets/videos/
  fonts: 
    - family: Roboto
      fonts: 
        - asset: assets/fonts/RobotoRegular.ttf
          weight: 400
        - asset: assets/fonts/RobotoMedium.ttf
          weight: 500
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterSemiBold.ttf
          weight: 600
        - asset: assets/fonts/InterMedium.ttf
          weight: 500
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
        - asset: assets/fonts/InterBold.ttf
          weight: 700
    - family: Cairo
      fonts: 
        - asset: assets/fonts/CairoLight.ttf
          weight: 300
    - family: SF Pro Display
      fonts: 
        - asset: assets/fonts/SFProDisplayBold.ttf
          weight: 700
    - family: SF Pro
      fonts: 
        - asset: assets/fonts/SFProRegular.ttf
          weight: 400
        - asset: assets/fonts/SFProBold.ttf
          weight: 700
    - family: SF Pro Text
      fonts: 
        - asset: assets/fonts/SFProTextRegular.ttf
          weight: 400
        - asset: assets/fonts/SFProTextBold.ttf
          weight: 600
    - family: Sakkal Majalla
      fonts: 
        - asset: assets/fonts/SakkalMajalla.ttf
          weight: 400
        - asset: assets/fonts/SakkalMajallaBold.ttf
          weight: 700
    - family: (A) Arslan Wessam B
      fonts: 
        - asset: assets/fonts/AArslanWessamBAArslanWessamB.ttf
          weight: 400
    - family: NavbarIcon
      fonts: 
        - asset: assets/fonts/NavbarIcon.ttf
