/// Flutter icons NavbarIcon
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  NavbarIcon
///      fonts:
///       - asset: fonts/NavbarIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class NavbarIcon {
  NavbarIcon._();

  static const _kFontFam = 'NavbarIcon';
  static const String? _kFontPkg = null;

  static const IconData img_material_symbol_gray_400_01 = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData img_settings = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData img_iconamoon_profile_fill = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData img_material_symbol = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
